### ISSUE TITLE
SignInWithApple undefined

### ISSUE THREAD

**Issue by gentlemanjohn** [htorbov/capacitor-apple-login#1]
Following the usage instructions I get this on Android:

> TypeError: Cannot read property 'Authorize' of undefined.

**Comment by htorbov** [comment]
@gentlemanjohn I completely forgot to mention that the plugin works on iOS only, lol... I've made it for my app just to pass Apple's new terms. Please see the updated [README.md](https://github.com/htorbov/capacitor-apple-login/blob/master/README.md) for instructions how to check if the user is on iOS device. Good luck!

**Comment by gentlemanjohn** [comment]
Ah OK, I will check it out.   If I get some time I'll see if I can tackle the android side.
