### ISSUE TITLE
Outdated NPM package

### ISSUE THREAD

**Issue by AlanAcDz** [htorbov/capacitor-apple-login#4]
Hi, I noticed the npm package does not contain the latest changes of the Plugin.swift file, specifically the response, line 40. The response in that file is:

> "response": [
                "user": appleIDCredential.user,
                "email": appleIDCredential.email,
                "givenName": appleIDCredential.fullName?.givenName,
                "familyName": appleIDCredential.fullName?.familyName,
                "identityToken": String(data: appleIDCredential.identityToken!, encoding: .utf8),
                "authorizationCode": String(data: appleIDCredential.authorizationCode!, encoding: .utf8)
            ]

However, in the npm version, the response in the same file is:

> "response": [
                "user": appleIDCredential.user,
                "email": appleIDCredential.email,
                "givenName": appleIDCredential.fullName?.givenName,
                "familyName": appleIDCredential.fullName?.familyName
            ]

Please update the npm package with the latest changes, the identityToken property is needed if you want to use a third-party auth provider

**Comment by ryandegruyter** [comment]
@htorbov
